import type { Status, StatusTone } from '@pms/shared';

/**
 * v2's domain types, constants, and pure derived-state helpers (SPEC.md).
 *
 * Nothing in this file talks to the API itself — `v2Store.tsx` does that —
 * but the task-template generators (`ptiTasks`/`cleaningTasks`/
 * `repairTasksFor`) are what a real Gate-In actually builds a new
 * container's sections from, and every `*Status`/`*Breakdown`/`*Load`
 * function here computes real derived state from whatever real data is
 * passed in. The demo/seed data this file used to also hold (`MOCK_WORKERS`,
 * `initialContainers()`, `initialDrafts()`) was removed once the app no
 * longer needed a mock fallback — `v2Store.tsx` now starts empty and fills
 * in from Supabase.
 */

export type WorkerType =
  | 'painter'
  | 'painter_helper'
  | 'technician'
  | 'all_rounder'
  | 'cleaner'
  | 'tea_boy'
  | 'sailing_crew';

export const WORKER_TYPES: WorkerType[] = [
  'painter',
  'painter_helper',
  'technician',
  'all_rounder',
  'cleaner',
  'tea_boy',
  'sailing_crew',
];

export const WORKER_TYPE_LABELS: Record<WorkerType, string> = {
  painter: 'Painter',
  painter_helper: 'Painter Helper',
  technician: 'Technician',
  all_rounder: 'All-Rounder',
  cleaner: 'Cleaner',
  tea_boy: 'Tea Boy',
  sailing_crew: 'Sailing Crew',
};

export interface MockWorker {
  id: string;
  name: string;
  type: WorkerType;
  active: boolean;
  notes: string;
}

export type SectionKind = 'painting' | 'pti' | 'cleaning' | 'all_rounder' | 'sailing';

/** The stage's own display name — kept distinct from WORKER_TYPE_LABELS on
 * purpose: "Repairment" is the stage physical repair work happens at, done
 * by an "All-Rounder" (the worker role). Same underlying SectionKind value,
 * so nothing about the data model needs two separate concepts — just two
 * separate labels for them. */
export const SECTION_LABELS: Record<SectionKind, string> = {
  painting: 'Painting',
  pti: 'PTI',
  cleaning: 'Cleaning',
  all_rounder: 'Repairment',
  sailing: 'Sailing Crew',
};

export const SECTION_OWNER_TYPE: Record<SectionKind, WorkerType> = {
  painting: 'painter',
  pti: 'technician',
  cleaning: 'cleaner',
  all_rounder: 'all_rounder',
  sailing: 'sailing_crew',
};

export type TaskState = 'pending' | 'running' | 'done' | 'na';

export interface MockTask {
  key: string;
  label: string;
  workerId: string | null;
  state: TaskState;
  /** Epoch ms the running timer started at; null unless state === 'running'. */
  startedAt: number | null;
  /** Accumulated seconds once stopped. */
  elapsedSec: number;
  /** ISO timestamp set the moment the task is stopped or marked N/A —
   * absent/undefined on tasks that aren't settled yet, and left unset on the
   * hand-authored mock containers below (we don't actually know when those
   * historically finished). Drives time-bounded stats (worker hours this
   * week/month, per-section turnaround) that `elapsedSec` alone can't
   * answer since it's a duration, not a point in time. */
  completedAt?: string | null;
  /** Can be marked Not Applicable instead of timed — e.g. the 2nd paint coat. */
  optional?: boolean;
  /** Average expected duration, for the dashboard's section-load panel. */
  estHrs: number;
  /** Where the container has to physically be to do this task. Fixed by
   * section for Painting/PTI/Cleaning, and for a Repairment task generated
   * from a flagged checklist item (repairTasksFor); null until the Admin
   * picks one for a genuinely ad-hoc Repairment task with no checklist item
   * behind it. */
  site: SailingSite | null;
  /** Overrides the section's default assignee type (SECTION_OWNER_TYPE) for
   * this one task — e.g. Painting's tape/compressor tasks go to a Painter
   * Helper, not the Painter who does Primer/coats/Logo (SPEC.md §4.3). */
  ownerType?: WorkerType;
  /** Explicit task keys (within the same section) this one waits on. When
   * set, this replaces plain array-order for sequencing — lets two tasks
   * that both only depend on an earlier step (e.g. Logo and painting the
   * compressor/display, both only gated on the main coats being done) run
   * in parallel instead of blocking each other. Tasks without this still
   * fall back to strict array order (paintingTaskBlockedBy below). */
  dependsOn?: string[];
  /** A plain 'YYYY-MM-DD' date — which day this task is actually planned
   * for, separate from whether it's been worked yet. Absent/undefined means
   * unscheduled: assigning a worker (v2Store's assignWorker) fills this in
   * with today unless it's already set, same "optional, filled in as it
   * becomes known" shape as completedAt above — a task generated by intake
   * or by the demo data never has to carry a fabricated date it doesn't
   * actually have yet. */
  scheduledFor?: string | null;
}

export interface MockSection {
  kind: SectionKind;
  tasks: MockTask[];
}

/** Not a plain pass/fail — "unassessed" is its own state (distinct from
 * "good") so a field nobody has actually looked at yet can never silently
 * read the same as one confirmed fine, matching the form's own rule that
 * nothing is assumed OK. `flagged` is a plain yes/no "needs repair" — the
 * Repair Required checklist uses only this and `good`, deliberately not the
 * minor/major split (Machine Check still uses minor/major; see
 * `RepairToggle` in GateFormDialog.tsx for why the two checklists diverged). */
export type FieldSeverity = 'unassessed' | 'good' | 'minor' | 'major' | 'flagged';

export const FIELD_SEVERITY_LABELS: Record<FieldSeverity, string> = {
  unassessed: 'Not yet checked',
  good: 'Good',
  minor: 'Minor damage',
  major: 'Major damage',
  flagged: 'Needs repair',
};

export interface MockSurveyField {
  label: string;
  severity: FieldSeverity;
  /** What's actually wrong, in the surveyor's own words — not shown/used
   * while severity is 'good' or 'unassessed'. */
  note: string;
}

/** A field needs attention — triggers Painting/Cleaning, shows up as
 * "Flagged" on the report — whenever it isn't confirmed good. An unassessed
 * field counts the same as a flagged one: nothing is assumed OK. */
export function fieldNeedsAttention(f: MockSurveyField): boolean {
  return f.severity !== 'good';
}

/** The depot's printed Container Inspection Checklist (SPEC.md §8.1) — every
 * container gets this half, surveyed before anything else. */
export const CONTAINER_INSPECTION_FIELDS = [
  'Outside / Undercarriage',
  'Inside and Outside Doors',
  'Right Side',
  'Left Side',
  'Front Wall',
  'Ceiling / Roof',
  'Floor (Inside)',
  'Contamination',
  'Gasket Door',
  'Curtain',
  'Tube Light',
  'Mantrap',
];

/** The depot's printed Machine Check — Reefer units only; a Dry or Tank unit
 * has no refrigeration machinery to check. */
export const MACHINE_CHECK_FIELDS = [
  'Compressor',
  'Condenser Coil',
  'Evaporator Coil',
  'Condenser Fan',
  'Evaporator Fan',
  'Controller / Microprocessor',
  'Power Cable & Plug',
  'Refrigerant Gas Charge',
  'Temperature Sensors / Probes',
  'Defrost System',
  'Cable 4 Core 4mm 18Mtr',
  'Motor Condition',
  'Contractor',
  'ISO Plug',
];

/** Container Inspection items whose fix is physical repair work — not paint,
 * not cleaning, and not one of the three (Curtain/Tube Light/Mantrap) that
 * already map onto an existing PTI task by name. Routed to the Repairment
 * stage, done by an All-Rounder. */
export const REPAIR_ITEMS = [
  'Outside / Undercarriage',
  'Inside and Outside Doors',
  'Right Side',
  'Left Side',
  'Front Wall',
  'Ceiling / Roof',
  'Floor (Inside)',
  'Gasket Door',
];

/** The full checklist for a container of this type. */
export function surveyFieldNames(isReefer: boolean): string[] {
  return isReefer ? [...CONTAINER_INSPECTION_FIELDS, ...MACHINE_CHECK_FIELDS] : CONTAINER_INSPECTION_FIELDS;
}

/** A full checklist result — every item good except the ones named in
 * `issues`, which carry their own severity and a note on what's wrong. */
export function surveyFields(
  isReefer: boolean,
  issues: Array<{ label: string; severity: 'minor' | 'major'; note: string }> = []
): MockSurveyField[] {
  const byLabel = new Map(issues.map((i) => [i.label, i]));
  return surveyFieldNames(isReefer).map((label) => {
    const issue = byLabel.get(label);
    return issue ? { label, severity: issue.severity, note: issue.note } : { label, severity: 'good', note: '' };
  });
}

export interface MockSurvey {
  performedAt: string;
  fields: MockSurveyField[];
  outcome: 'ready' | 'needs-work';
}

export type LogoChoice = 'na' | 'readymade' | 'physical' | 'removal';

/** Matches the depot's live Gate In/Out portal: a plain Yes/No, with Yes
 * requiring a PTI video alongside it. */
export type PtiCheckAnswer = 'Yes' | 'No';

export type GatePhotoKey =
  | 'leftSide'
  | 'rightSide'
  | 'backView'
  | 'insideFront'
  | 'insideRear'
  | 'roof'
  | 'floor'
  | 'doorLock'
  | 'closeUp';

/** The depot's required Inspection Photos — the same nine shots at both Gate
 * In and Gate Out, so entry and exit condition can be compared side by
 * side. */
export const GATE_PHOTO_SLOTS: Array<{ key: GatePhotoKey; label: string }> = [
  { key: 'leftSide', label: 'Left Side' },
  { key: 'rightSide', label: 'Right Side' },
  { key: 'backView', label: 'Back View' },
  { key: 'insideFront', label: 'Inside Front' },
  { key: 'insideRear', label: 'Inside Rear' },
  { key: 'roof', label: 'Roof' },
  { key: 'floor', label: 'Floor' },
  { key: 'doorLock', label: 'Door Lock' },
  { key: 'closeUp', label: 'Container Close-up' },
];

/** Every photo's value is an object URL from `URL.createObjectURL` — mock
 * capture only, never a real upload (no backend in this preview). */
export type GatePhotos = Record<GatePhotoKey, string> & { additional: string[] };

/**
 * One full submission of the Gate In/Gate Out form (SPEC: "Digital Lifecycle
 * Tracker"). Deliberately additive, not a replacement for `MockSurvey` —
 * `repairFields`/`machineFields` here are the same arrays folded into
 * `MockContainer.survey.fields` (via `surveyFields()`) at submit time; kept
 * here too so the Gate In/Out record itself renders standalone on the
 * report.
 */
export interface GateLogEntry {
  kind: 'in' | 'out';
  /** ISO timestamp set the moment the form is confirmed. */
  loggedAt: string;
  /** "Email / Name" — one combined field in the real form, defaults to the
   * signed-in user's email but stays freely editable (whoever's physically
   * at the gate may not be who's logged into the app). */
  loggedBy: string;
  /** The calendar date of `loggedAt`, auto-derived at submit time — not an
   * editable field. Gate-In/Out is a real physical event, so it's never
   * back- or post-datable; kept as its own column (rather than reading
   * `loggedAt` everywhere) since the report displays a plain date, and
   * deriving it once at the source is simpler than reformatting a
   * timestamp at every call site. */
  movementDate: string;
  indentRef: string;
  customerName: string;
  location: string;
  transporterName: string;
  transporterNumber: string;
  vehicleNumber: string;
  /** Filename only — never an actual upload. */
  lrCopyName: string | null;
  ptiCheck: PtiCheckAnswer;
  /** The file's original name, kept for display even after upload. */
  ptiVideoName: string | null;
  /** A real, permanent Google Drive link once the video's actually been
   * uploaded (GateFormDialog's buildPhotos/confirmGateIn) — null for every
   * record predating that, and for anything saved before `ptiVideoName`
   * is set. */
  ptiVideoUrl: string | null;
  photos: GatePhotos;
  /** Null on Gate Out — repairs are assumed closed out before a container
   * ever clears Ready to Move, so it isn't asked again on the way out. */
  repairRequired: boolean | null;
  repairFields: MockSurveyField[];
  machineIssueFound: boolean | null;
  machineFields: MockSurveyField[];
  cleaningRequired: boolean | null;
  /** Free text, matching the real form (not a parsed number). */
  estBudget: string;
  remarks: string;
}

/** A snapshot of the intake form's fields, saved before the admin finished
 * registering a container (interrupted by a call, the next arrival, etc.) —
 * everything needed to pre-fill GateFormDialog back to where they left off.
 * Photos are deliberately not included — a `File` can't round-trip through a
 * saved draft, so resuming always reopens with every photo slot empty. */
export interface ContainerDraftData {
  id: string;
  typeCode: string;
  size: string;
  color: string;
  customColor: string;
  logoChoice: LogoChoice;
  priority: boolean;
  fields: MockSurveyField[];
  loggedBy: string;
  indentRef: string;
  customerName: string;
  location: string;
  transporterName: string;
  transporterNumber: string;
  vehicleNumber: string;
  ptiCheck: PtiCheckAnswer;
  repairRequired: boolean;
  machineIssueFound: boolean;
  cleaningRequired: boolean;
  estBudget: string;
  remarks: string;
}

export interface ContainerDraft {
  id: string;
  savedAt: string;
  data: ContainerDraftData;
}

export interface MockContainer {
  id: string;
  /** PENDING — placeholder product/type code until the depot's full list lands. */
  typeCode: string;
  size: string;
  /** Painting colour (SPEC.md §4.3): reefers default to white; dry/tank units
   * carry whatever the customer asked for, picked or typed in at intake. Null
   * until survey has run. */
  color: string | null;
  survey: MockSurvey | null;
  sections: MockSection[];
  readyAt: string | null;
  /** A completion photo is required before a container can be marked ready
   * (client request) — set together with `readyAt` in the same action, so
   * this is never non-null while `readyAt` is still null, or vice versa. */
  readyPhotoUrl: string | null;
  /** Where the container physically is right now. Null means it hasn't been
   * moved to any of the yard's work sites yet (fresh off gate-in). */
  currentSite: SailingSite | null;
  /** Fast-track/urgent — set at intake or toggled later from Container Detail.
   * Surfaces as a marker on Yard Board/Live Board and sorts first. */
  priority: boolean;
  /** ISO timestamp set at gate-in — the only reliable "how long has this
   * been sitting" baseline for a container that hasn't been surveyed yet
   * (survey.performedAt doesn't exist until the survey actually runs). */
  registeredAt: string;
  /** The digital Gate In record. Null for every pre-existing demo container
   * (gated in before this form existed) — same precedent as `survey: MockSurvey | null`. */
  gateIn: GateLogEntry | null;
  /** Set the moment Gate Out is confirmed. */
  gateOut: GateLogEntry | null;
  /** ISO timestamp the container left the yard — the archive flag. Null
   * means still active. Independent of `gateOut`: a legacy container can be
   * departed with no digital record behind it. */
  departedAt: string | null;
}

export const STANDARD_COLORS = ['White', 'Grey', 'Blue', 'Green', 'Beige', 'Red'];

/** SPEC.md §8 item 9, resolved: the depot's actual Type list, matching the
 * live Gate-In/Gate-Out portal's own dropdown. Shared by the intake form and
 * Container Detail's edit form. "Machine" and "Other" were both in the real
 * portal's own dropdown source but aren't products this depot actually
 * handles — both removed on direct correction; the portal's source
 * evidently covers more than this one depot's real offering. */
export const TYPE_CODES = ['Dry', 'Reefer', 'ISO Tank', 'Porta Cabin'];

/** Also from the real portal — not type-dependent, same four options
 * regardless of what Type is picked. */
export const SIZE_OPTIONS = ['10 Feet', '20 Feet', '40 Feet', 'Other'];

export const SAILING_SITES = ['Painting site', 'Washing site', 'Strip site', 'Light site'] as const;
export type SailingSite = (typeof SAILING_SITES)[number];
/** Shown as the "from" side of a movement, and as the container's location,
 * whenever it hasn't been moved to a named site yet. */
export const GATE_SITE = 'Gate' as const;

/* -------------------------------------------------------------------------- */
/* Task templates per section                                                 */
/* -------------------------------------------------------------------------- */

export function ptiTasks(withWorker: string | null, mantrap: boolean): MockTask[] {
  // PTI's two checks happen in different physical spots — lights and
  // strip/curtain are not the same site, so this is task-level, not
  // section-level, unlike Painting and Cleaning.
  const tasks: MockTask[] = [
    { key: 'lights', label: 'Lights', workerId: withWorker, state: 'pending', startedAt: null, elapsedSec: 0, estHrs: 1, site: 'Light site' },
    { key: 'strip_curtain', label: 'Strip & curtain', workerId: withWorker, state: 'pending', startedAt: null, elapsedSec: 0, estHrs: 1, site: 'Strip site' },
  ];
  if (mantrap) {
    tasks.push({ key: 'mantrap', label: 'Mantrap', workerId: withWorker, state: 'pending', startedAt: null, elapsedSec: 0, estHrs: 1, site: 'Strip site' });
  }
  return tasks;
}

export function cleaningTasks(withWorker: string | null): MockTask[] {
  return [{ key: 'clean', label: 'Clean container', workerId: withWorker, state: 'pending', startedAt: null, elapsedSec: 0, estHrs: 1, site: 'Washing site' }];
}

/** One task per flagged checklist item named in `itemNames` — the actual
 * fix, not just a record that something's wrong. Shared by Repairment
 * (REPAIR_ITEMS, Painting site) and PTI's Machine Check add-ons
 * (MACHINE_CHECK_FIELDS, Light site). */
export function repairTasksFor(fields: MockSurveyField[], itemNames: string[], site: SailingSite): MockTask[] {
  return fields
    .filter((f) => itemNames.includes(f.label) && fieldNeedsAttention(f))
    .map((f) => ({
      key: `repair_${f.label.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '')}`,
      label: `Repair: ${f.label}`,
      workerId: null,
      state: 'pending' as const,
      startedAt: null,
      elapsedSec: 0,
      estHrs: 1,
      site,
    }));
}

/* -------------------------------------------------------------------------- */
/* Pure helpers                                                                */
/* -------------------------------------------------------------------------- */

export function taskElapsedSec(task: MockTask, nowMs: number): number {
  if (task.state === 'running' && task.startedAt) {
    return task.elapsedSec + Math.floor((nowMs - task.startedAt) / 1000);
  }
  return task.elapsedSec;
}

/** `survey.performedAt` is a plain date ('2026-09-28') on every
 * hand-authored mock container, but a full ISO timestamp on anything gated
 * in through the intake form since — show the time too when there
 * genuinely is one, instead of printing midnight for every new survey. */
export function formatSurveyDate(performedAt: string): string {
  const d = new Date(performedAt);
  if (Number.isNaN(d.getTime())) return performedAt;
  const iso = d.toISOString();
  return performedAt.includes('T') ? `${iso.slice(0, 10)} ${iso.slice(11, 16)}` : iso.slice(0, 10);
}

export function formatElapsed(sec: number): string {
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = Math.floor(sec % 60);
  if (h > 0) return `${h}h ${String(m).padStart(2, '0')}m`;
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
}

export function taskSettled(task: MockTask): boolean {
  return task.state === 'done' || task.state === 'na';
}

/** The one place "is this task scheduled for that day" is decided — every
 * day-scoped view (the daily roster, the reschedule menu) reads through
 * this rather than comparing `scheduledFor` by hand. */
export function isScheduledFor(task: MockTask, date: string): boolean {
  return task.scheduledFor === date;
}

/** A plain 'YYYY-MM-DD' date `days` from today — the same shape `scheduledFor`
 * is stored in, so it can be compared and written back directly. Shared by
 * every quick-pick date control (the reschedule chip, AssignWorkDialog). */
export function offsetDate(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

/** The near-term planning horizon every date quick-pick offers — "daily
 * basis" assignment, not a full calendar. */
export const RESCHEDULE_OFFSETS: Array<{ days: number; label: string }> = [
  { days: 0, label: 'Today' },
  { days: 1, label: 'Tomorrow' },
  { days: 2, label: 'In 2 days' },
  { days: 3, label: 'In 3 days' },
];

/** "Today"/"Tomorrow" read faster than a raw date for the only two days most
 * planning actually happens on; anything further out just shows the date. */
export function scheduleLabel(date: string | null | undefined): string {
  if (!date) return 'Unscheduled';
  if (date === offsetDate(0)) return 'Today';
  if (date === offsetDate(1)) return 'Tomorrow';
  return date;
}

/** Painting only (SPEC.md §4.3): Primer → 1st coat → 2nd coat → Logo run in a
 * fixed order, unlike every other section's tasks. Returns the earliest task
 * still holding this one up, or null if it's clear to start.
 *
 * Walks the *whole* ancestor chain, not just the immediate dependency —
 * a dependency counting as "settled" (done, or marked N/A as skipped) says
 * nothing about whether its own dependency was ever actually satisfied. An
 * optional step can be marked N/A the moment it's reachable, independent of
 * whether the step before *it* has finished; checking only one level would
 * report Logo as clear to start the instant 2nd coat is marked N/A, even
 * while 1st coat is still running underneath it. */
export function paintingTaskBlockedBy(section: MockSection, task: MockTask): MockTask | null {
  if (section.kind !== 'painting') return null;
  const deps: MockTask[] = task.dependsOn
    ? task.dependsOn.map((key) => section.tasks.find((t) => t.key === key)).filter((t): t is MockTask => Boolean(t))
    : section.tasks.slice(0, section.tasks.findIndex((t) => t.key === task.key));
  for (const dep of deps) {
    if (!taskSettled(dep)) return dep;
    const upstream = paintingTaskBlockedBy(section, dep);
    if (upstream) return upstream;
  }
  return null;
}

export function sectionStatus(section: MockSection): Status {
  const total = section.tasks.length;
  const settled = section.tasks.filter(taskSettled).length;
  const running_ = section.tasks.some((t) => t.state === 'running');
  if (total > 0 && settled === total) {
    return { tone: 'ok', icon: 'check-circle', label: 'Done', detail: `${SECTION_LABELS[section.kind]}: every task complete.` };
  }
  if (running_) {
    return { tone: 'info', icon: 'clock', label: `${settled}/${total}`, detail: `${SECTION_LABELS[section.kind]}: a task is running now, ${settled} of ${total} complete.` };
  }
  if (settled > 0) {
    return { tone: 'warn', icon: 'clock', label: `${settled}/${total}`, detail: `${SECTION_LABELS[section.kind]}: ${settled} of ${total} tasks complete, none running.` };
  }
  return { tone: 'neutral', icon: 'clock', label: `0/${total}`, detail: `${SECTION_LABELS[section.kind]}: not started.` };
}

export function isReadyToMove(container: MockContainer): boolean {
  if (!container.survey) return false;
  if (container.survey.outcome === 'ready') return true;
  if (container.sections.length === 0) return false;
  // A section with no tasks yet isn't "done" — it's unactioned. Without this,
  // `[].every(...)` is vacuously true and a section that was flagged but
  // never given a task would count as complete.
  return container.sections.every((s) => s.tasks.length > 0 && s.tasks.every(taskSettled));
}

/** Days since this container last moved stage — gate-in (`registeredAt`) if
 * it hasn't been surveyed yet, otherwise the survey date. Zero once it's
 * ready, since aging stops mattering the moment there's nothing left
 * waiting. Thresholds (3d warn, 7d bad) are a starting guess, not a number
 * from the depot — tune freely. */
export function agingDays(container: MockContainer, nowMs: number = Date.now()): number {
  if (container.readyAt) return 0;
  const baseline = container.survey ? container.survey.performedAt : container.registeredAt;
  const baselineMs = new Date(baseline).getTime();
  if (Number.isNaN(baselineMs)) return 0;
  return Math.max(0, Math.floor((nowMs - baselineMs) / (1000 * 60 * 60 * 24)));
}

/** Null when there's nothing to flag — under the warn threshold, or already
 * ready to move. */
export function agingStatus(container: MockContainer): Status | null {
  const days = agingDays(container);
  if (days < 3) return null;
  const tone: StatusTone = days >= 7 ? 'bad' : 'warn';
  const stage = container.survey ? 'in progress' : 'awaiting survey';
  return { tone, icon: 'clock', label: `${days}d ${stage}`, detail: `${container.id} has been ${stage} for ${days} day(s).` };
}

export function isDeparted(container: MockContainer): boolean {
  return container.departedAt !== null;
}

export function overallStatus(container: MockContainer): Status {
  if (container.departedAt) {
    return { tone: 'neutral', icon: 'truck', label: 'Departed', detail: `${container.id} gated out on ${formatSurveyDate(container.departedAt)}.` };
  }
  if (container.readyAt || isReadyToMove(container)) {
    return { tone: 'ok', icon: 'check-circle', label: 'Ready to move', detail: `${container.id} has cleared every required section.` };
  }
  if (!container.survey) {
    return { tone: 'neutral', icon: 'doc', label: 'Awaiting survey', detail: `${container.id} has not been surveyed yet.` };
  }
  const anyRunning = container.sections.some((s) => s.tasks.some((t) => t.state === 'running'));
  return {
    tone: anyRunning ? 'info' : 'warn',
    icon: 'clock',
    label: anyRunning ? 'In progress' : 'Open',
    detail: `${container.id} has open work in ${container.sections.length} section(s).`,
  };
}

export function openTaskCount(container: MockContainer): number {
  return container.sections.reduce((n, s) => n + s.tasks.filter((t) => !taskSettled(t)).length, 0);
}

export interface PtiBreakdown {
  total: number;
  ptiPending: number;
  lightsPendingOnly: number;
  curtainPendingOnly: number;
  fullyOk: number;
}

export function ptiBreakdown(containers: MockContainer[]): PtiBreakdown {
  let ptiPending = 0;
  let lightsPendingOnly = 0;
  let curtainPendingOnly = 0;
  let fullyOk = 0;
  for (const c of containers) {
    const pti = c.sections.find((s) => s.kind === 'pti');
    if (!pti) {
      fullyOk += 1;
      continue;
    }
    const lights = pti.tasks.find((t) => t.key === 'lights');
    const strip = pti.tasks.find((t) => t.key === 'strip_curtain');
    const lightsDone = !lights || taskSettled(lights);
    const stripDone = !strip || taskSettled(strip);
    if (!lightsDone && !stripDone) ptiPending += 1;
    else if (!lightsDone && stripDone) lightsPendingOnly += 1;
    else if (lightsDone && !stripDone) curtainPendingOnly += 1;
    else fullyOk += 1;
  }
  return { total: containers.length, ptiPending, lightsPendingOnly, curtainPendingOnly, fullyOk };
}

export interface SectionLoad {
  kind: SectionKind;
  pendingTasks: number;
  avgEstHrs: number;
}

export function sectionLoad(containers: MockContainer[]): SectionLoad[] {
  const kinds: SectionKind[] = ['painting', 'pti', 'cleaning', 'all_rounder', 'sailing'];
  return kinds.map((kind) => {
    const openTasks = containers
      .flatMap((c) => c.sections.filter((s) => s.kind === kind))
      .flatMap((s) => s.tasks)
      .filter((t) => !taskSettled(t));
    const avg = openTasks.length ? openTasks.reduce((sum, t) => sum + t.estHrs, 0) / openTasks.length : 0;
    return { kind, pendingTasks: openTasks.length, avgEstHrs: Math.round(avg * 10) / 10 };
  });
}

export interface SectionContainerCounts {
  kind: SectionKind;
  /** Container has a task actively running in this section right now. */
  inProcess: number;
  /** Container has this section, nothing running, not fully settled yet —
   * i.e. still waiting its turn. */
  inLine: number;
  /** Every task in this section is done or N/A. */
  done: number;
}

/** How many containers sit at each stage, not how many tasks — the "how many
 * are in process vs. still in line" breakdown for the admin's overview. */
export function sectionContainerCounts(containers: MockContainer[]): SectionContainerCounts[] {
  const kinds: SectionKind[] = ['painting', 'pti', 'cleaning', 'all_rounder', 'sailing'];
  return kinds.map((kind) => {
    let inProcess = 0;
    let inLine = 0;
    let done = 0;
    for (const c of containers) {
      const section = c.sections.find((s) => s.kind === kind);
      if (!section || section.tasks.length === 0) continue;
      if (section.tasks.some((t) => t.state === 'running')) inProcess += 1;
      else if (section.tasks.every(taskSettled)) done += 1;
      else inLine += 1;
    }
    return { kind, inProcess, inLine, done };
  });
}

export interface SectionTurnaround {
  kind: SectionKind;
  completedCount: number;
  avgHrs: number;
}

/** Average *actual* time a completed task in each section took
 * (`elapsedSec`, not the `estHrs` guess) — the yard report's "how long does
 * this really take" number. */
export function sectionTurnaround(containers: MockContainer[]): SectionTurnaround[] {
  const kinds: SectionKind[] = ['painting', 'pti', 'cleaning', 'all_rounder', 'sailing'];
  return kinds.map((kind) => {
    const doneTasks = containers
      .flatMap((c) => c.sections.filter((s) => s.kind === kind))
      .flatMap((s) => s.tasks)
      .filter((t) => t.state === 'done');
    const avgHrs = doneTasks.length ? doneTasks.reduce((sum, t) => sum + t.elapsedSec, 0) / doneTasks.length / 3600 : 0;
    return { kind, completedCount: doneTasks.length, avgHrs: Math.round(avgHrs * 10) / 10 };
  });
}

export interface GateActivity {
  gatedInToday: number;
  gatedOutToday: number;
}

/** How many containers crossed the gate today, specifically — reads
 * `registeredAt`/`departedAt` (always set on every container) rather than
 * `gateIn`/`gateOut` (the detailed form record, which stays null for
 * anything not registered through the live Gate-In form, including most of
 * today's seed data), so this reflects real activity even before any
 * container has gone through that form. */
export function gateActivityToday(containers: MockContainer[]): GateActivity {
  const today = offsetDate(0);
  return {
    gatedInToday: containers.filter((c) => c.registeredAt.slice(0, 10) === today).length,
    gatedOutToday: containers.filter((c) => c.departedAt?.slice(0, 10) === today).length,
  };
}

function parseBudget(estBudget: string | undefined): number | null {
  if (!estBudget) return null;
  const digits = estBudget.replace(/[^0-9.]/g, '');
  const n = Number(digits);
  return digits !== '' && Number.isFinite(n) ? n : null;
}

export interface BudgetExposure {
  /** How many active containers actually carry a parseable estimate — the
   * free-text `estBudget` field is often left blank, and it only exists at
   * all on containers that went through the live Gate-In form (`gateIn`),
   * so this is never assumed to be every container in the yard. */
  estimatedCount: number;
  totalInProgress: number;
  totalReady: number;
}

/** Live cost exposure across the yard, split by whether the container has
 * already cleared its work — the in-progress total is money still being
 * spent, the ready total is money already spent sitting in the yard waiting
 * on gate-out. Reads only the admin's own `gateIn.estBudget` estimate,
 * never invented or defaulted for containers that don't have one. */
export function budgetExposure(containers: MockContainer[]): BudgetExposure {
  let estimatedCount = 0;
  let totalInProgress = 0;
  let totalReady = 0;
  for (const c of containers) {
    const amount = parseBudget(c.gateIn?.estBudget);
    if (amount === null) continue;
    estimatedCount += 1;
    if (c.readyAt || isReadyToMove(c)) totalReady += amount;
    else totalInProgress += amount;
  }
  return { estimatedCount, totalInProgress, totalReady };
}

export interface ReadyNotGatedOut {
  container: MockContainer;
  daysSinceReady: number;
}

/** A container stops "aging" the moment it's ready (`agingDays` zeroes out
 * right then) — which is correct for "is anyone behind on work," but it
 * means nothing currently measures the *next* gap: cleared for release, yet
 * still occupying yard space until someone actually gates it out. */
export function readyNotGatedOut(containers: MockContainer[], nowMs: number = Date.now()): ReadyNotGatedOut[] {
  return containers
    .filter((c) => (c.readyAt || isReadyToMove(c)) && !c.gateOut && !c.departedAt)
    .map((c) => {
      const baselineMs = c.readyAt ? new Date(c.readyAt).getTime() : nowMs;
      const daysSinceReady = Number.isNaN(baselineMs) ? 0 : Math.max(0, Math.floor((nowMs - baselineMs) / (1000 * 60 * 60 * 24)));
      return { container: c, daysSinceReady };
    })
    .sort((a, b) => b.daysSinceReady - a.daysSinceReady);
}

/* -------------------------------------------------------------------------- */
/* Live cross-cuts — the same task data, re-sliced by section or by worker    */
/* -------------------------------------------------------------------------- */

export interface LiveTask {
  containerId: string;
  containerTypeCode: string;
  section: SectionKind;
  task: MockTask;
}

/** Every task in a given section, across every container, worker assignments
 * and all — the "stage-wise" live view. */
export function tasksBySection(containers: MockContainer[], kind: SectionKind): LiveTask[] {
  const rows: LiveTask[] = [];
  for (const c of containers) {
    const section = c.sections.find((s) => s.kind === kind);
    if (!section) continue;
    for (const task of section.tasks) {
      rows.push({ containerId: c.id, containerTypeCode: c.typeCode, section: kind, task });
    }
  }
  return rows;
}

/** Every task assigned to one worker, across every container and section —
 * the "crew-wise" live view. Running tasks first, then pending, then settled
 * (done/N-A), each group newest-first isn't tracked so insertion order
 * stands in for it. */
export function tasksForWorker(containers: MockContainer[], workerId: string): LiveTask[] {
  const rows: LiveTask[] = [];
  for (const c of containers) {
    for (const section of c.sections) {
      for (const task of section.tasks) {
        if (task.workerId === workerId) {
          rows.push({ containerId: c.id, containerTypeCode: c.typeCode, section: section.kind, task });
        }
      }
    }
  }
  const rank = (t: LiveTask): number => (t.task.state === 'running' ? 0 : t.task.state === 'pending' ? 1 : 2);
  return [...rows].sort((a, b) => rank(a) - rank(b));
}

export interface CrewLoad {
  worker: MockWorker;
  running: LiveTask[];
  pending: LiveTask[];
  doneToday: LiveTask[];
}

/** One row per worker, their tasks already split by state — what the "by
 * crew" live view and the worker detail record are both built from. */
export function crewLoad(containers: MockContainer[], workers: MockWorker[]): CrewLoad[] {
  return workers.map((worker) => {
    const tasks = tasksForWorker(containers, worker.id);
    return {
      worker,
      running: tasks.filter((t) => t.task.state === 'running'),
      pending: tasks.filter((t) => t.task.state === 'pending'),
      doneToday: tasks.filter((t) => t.task.state === 'done'),
    };
  });
}

/** Active workers with nothing running and nothing scheduled for today —
 * the admin's "who can I actually hand new work to right now" list. Scoped
 * to today specifically rather than "zero pending ever": a worker with next
 * week's tasks already lined up isn't idle today just because nothing of
 * theirs happens to be running this literal second. */
export function idleWorkersToday(containers: MockContainer[], workers: MockWorker[]): MockWorker[] {
  const today = offsetDate(0);
  return workers.filter((w) => {
    if (!w.active) return false;
    const tasks = tasksForWorker(containers, w.id);
    return !tasks.some((t) => t.task.state === 'running' || isScheduledFor(t.task, today));
  });
}

export interface WorkerCompletion {
  worker: MockWorker;
  completedCount: number;
}

/** Tasks a worker actually finished in the last `days` days, by
 * `completedAt` (a point in time, unlike `elapsedSec`'s duration) — ranked,
 * so comparing the whole crew's recent output doesn't mean opening every
 * worker's own detail drawer one at a time. Workers with zero completions
 * in the window are left out rather than padding the list with zeroes. */
export function topPerformers(containers: MockContainer[], workers: MockWorker[], days: number, nowMs: number = Date.now()): WorkerCompletion[] {
  const cutoffMs = nowMs - days * 24 * 60 * 60 * 1000;
  return workers
    .map((worker) => {
      const completedCount = tasksForWorker(containers, worker.id).filter((t) => {
        if (!t.task.completedAt) return false;
        const completedMs = new Date(t.task.completedAt).getTime();
        return !Number.isNaN(completedMs) && completedMs >= cutoffMs;
      }).length;
      return { worker, completedCount };
    })
    .filter((w) => w.completedCount > 0)
    .sort((a, b) => b.completedCount - a.completedCount);
}
